# Generated by Django 5.0.4 on 2024-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('VERY BAD', 'Very Bad'), ('BAD', 'Bad'), ('OK', 'Ok'), ('GOOD', 'Good'), ('VERY GOOD', 'Very Good')]),
        ),
    ]
